### ISSUE TITLE
Windows error

### ISSUE THREAD

**Issue by jeffmaury** [maxandersen/gh-jtriage#1]
Tried it on Windows and seems to work (probably because I have git (bash) installed but the following error is displayed:

```
[jbang] [ERROR] Script or alias could not be found or read: 'C:\Users\JeffMAURY\AppData\Local\GitHub'
[jbang] Run with --verbose for more details
```

Probably a path with space error

**Comment by maxandersen** [comment]
this is a jbang error afaics, not releated to this specific plugin?
